import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/page";
import Footer from "./components/Footer/page";
import Navbar from "./components/Navbar/page";


export const metadata: Metadata = {
  title: "Hekto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
